### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by jennyfountain** [terraform-providers/terraform-provider-rundeck#8]
No issue just question. I don't see where you can setup notifications. Can this not be done?

**Comment by jennyfountain** [comment]
Anyone aware of how to do this?

**Comment by jennyfountain** [comment]
:( Anyone know how to add notification?

**Comment by apparentlymart** [comment]
Hi @jennyfountain,

I'm not familiar with Rundeck's notifications feature so I'm not sure, but if you don't see a resource for it (or an attribute on another resource, if notifications are a property of some other object) then I expect it's not currently supported.

This provider has no dedicated maintainers working on it right now, so we're aware that it's falling behind Rundeck's featureset. :confounded: We are open to adding new features, but with no dedicated maintainers and lacking in-house Rundeck expertise it can be challenging to test and merge changes. If any Rundeck experts in the community are interested in volunteering to help maintain this provider, please get in touch!
